language: cpp
sudo: false
script:
- git config --global user.email "deploy@travis-ci.org"
- git config --global user.name "Travis CI"
- git clone https://github.com/heavywatal/json.git release
- cp -a src/json_fwd.hpp src/json.hpp LICENSE.MIT README.md release/
- cd release/
- git add --all
- git commit -m "Travis CI ($TRAVIS_JOB_NUMBER)"
after_success:
- openssl aes-256-cbc -K $encrypted_1a0ca1a8b3b8_key -iv $encrypted_1a0ca1a8b3b8_iv -in deploy_key.enc -out ~/.ssh/id_ed25519 -d
- chmod 600 ~/.ssh/id_ed25519
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git push origin release
branches:
  only: travis
notifications:
  email: false
